name = Simple
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = simple-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[youtube]        = youtube
regions[facebook]       = facebook
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/simple/simple.layout.css
